using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace Marketplace.Infrastructure.Migrations
{
    /// <inheritdoc />
    public partial class AddShipmentStatusLog : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            // Idempotent: add "CurrentStatus" only if it does not already exist
            migrationBuilder.Sql(@"
                DO $$
                BEGIN
                    IF NOT EXISTS (SELECT 1 FROM information_schema.columns 
                                   WHERE table_name='Orders' AND column_name='CurrentStatus') THEN
                        ALTER TABLE ""Orders"" ADD ""CurrentStatus"" TEXT NOT NULL DEFAULT '';
                    END IF;
                END
                $$;
            ");

            // Create the ShipmentStatusLogs table if it doesn't exist
            migrationBuilder.Sql(@"
                CREATE TABLE IF NOT EXISTS ""ShipmentStatusLogs"" (
                    ""Id"" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    ""OrderId"" INTEGER NOT NULL,
                    ""Status"" TEXT NOT NULL,
                    ""Note"" TEXT NULL,
                    ""CreatedAt"" TIMESTAMP NOT NULL,
                    ""UpdatedByUserId"" INTEGER NOT NULL,
                    CONSTRAINT ""FK_ShipmentStatusLogs_Orders_OrderId"" FOREIGN KEY (""OrderId"") 
                        REFERENCES ""Orders"" (""Id"") ON DELETE CASCADE,
                    CONSTRAINT ""FK_ShipmentStatusLogs_Users_UpdatedByUserId"" FOREIGN KEY (""UpdatedByUserId"") 
                        REFERENCES ""Users"" (""Id"") ON DELETE RESTRICT
                );
            ");

            // Create indexes
            migrationBuilder.Sql(@"
                CREATE INDEX IF NOT EXISTS ""IX_ShipmentStatusLogs_OrderId"" 
                    ON ""ShipmentStatusLogs"" (""OrderId"");
                CREATE INDEX IF NOT EXISTS ""IX_ShipmentStatusLogs_UpdatedByUserId"" 
                    ON ""ShipmentStatusLogs"" (""UpdatedByUserId"");
            ");
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            // Drop the table if it exists
            migrationBuilder.Sql(@"DROP TABLE IF EXISTS ""ShipmentStatusLogs"";");

            // Drop the column if it exists
            migrationBuilder.Sql(@"
                DO $$
                BEGIN
                    IF EXISTS (SELECT 1 FROM information_schema.columns 
                               WHERE table_name='Orders' AND column_name='CurrentStatus') THEN
                        ALTER TABLE ""Orders"" DROP COLUMN ""CurrentStatus"";
                    END IF;
                END
                $$;
            ");
        }
    }
}