using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace Marketplace.Infrastructure.Migrations
{
    /// <inheritdoc />
    public partial class AddChatSystem : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            // Create Conversations table if not exists
            migrationBuilder.Sql(@"
                CREATE TABLE IF NOT EXISTS ""Conversations"" (
                    ""Id"" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    ""UserId1"" INTEGER NOT NULL,
                    ""UserId2"" INTEGER NOT NULL,
                    ""CreatedAt"" TIMESTAMP NOT NULL,
                    ""LastMessageAt"" TIMESTAMP NULL,
                    CONSTRAINT ""FK_Conversations_Users_UserId1"" FOREIGN KEY (""UserId1"") 
                        REFERENCES ""Users"" (""Id"") ON DELETE RESTRICT,
                    CONSTRAINT ""FK_Conversations_Users_UserId2"" FOREIGN KEY (""UserId2"") 
                        REFERENCES ""Users"" (""Id"") ON DELETE RESTRICT
                );
            ");

            // Create Messages table if not exists
            migrationBuilder.Sql(@"
                CREATE TABLE IF NOT EXISTS ""Messages"" (
                    ""Id"" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    ""ConversationId"" INTEGER NOT NULL,
                    ""SenderId"" INTEGER NOT NULL,
                    ""Content"" TEXT NOT NULL,
                    ""SentAt"" TIMESTAMP NOT NULL,
                    ""IsRead"" BOOLEAN NOT NULL,
                    CONSTRAINT ""FK_Messages_Conversations_ConversationId"" FOREIGN KEY (""ConversationId"") 
                        REFERENCES ""Conversations"" (""Id"") ON DELETE CASCADE,
                    CONSTRAINT ""FK_Messages_Users_SenderId"" FOREIGN KEY (""SenderId"") 
                        REFERENCES ""Users"" (""Id"") ON DELETE RESTRICT
                );
            ");

            // Create indexes if they don't exist
            // For Conversations
            migrationBuilder.Sql(@"
                DO $$
                BEGIN
                    IF NOT EXISTS (SELECT 1 FROM pg_indexes WHERE indexname = 'IX_Conversations_UserId1_UserId2') THEN
                        CREATE UNIQUE INDEX ""IX_Conversations_UserId1_UserId2"" 
                            ON ""Conversations"" (""UserId1"", ""UserId2"");
                    END IF;
                    IF NOT EXISTS (SELECT 1 FROM pg_indexes WHERE indexname = 'IX_Conversations_UserId2') THEN
                        CREATE INDEX ""IX_Conversations_UserId2"" 
                            ON ""Conversations"" (""UserId2"");
                    END IF;
                END
                $$;
            ");

            // For Messages
            migrationBuilder.Sql(@"
                DO $$
                BEGIN
                    IF NOT EXISTS (SELECT 1 FROM pg_indexes WHERE indexname = 'IX_Messages_ConversationId') THEN
                        CREATE INDEX ""IX_Messages_ConversationId"" 
                            ON ""Messages"" (""ConversationId"");
                    END IF;
                    IF NOT EXISTS (SELECT 1 FROM pg_indexes WHERE indexname = 'IX_Messages_SenderId') THEN
                        CREATE INDEX ""IX_Messages_SenderId"" 
                            ON ""Messages"" (""SenderId"");
                    END IF;
                END
                $$;
            ");
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            // Drop tables if they exist
            migrationBuilder.Sql(@"DROP TABLE IF EXISTS ""Messages"";");
            migrationBuilder.Sql(@"DROP TABLE IF EXISTS ""Conversations"";");
        }
    }
}